# -*- coding: utf-8 -*-
"""Exercise 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17TFONhZ_8FvxzNDMUe4XYqfUFhDXn6hw
"""

print("Exercise 1\n")
print("Twinkle, twinkle, little star,\nHow I wonder what you are! \nUp above the world so high, \nLike a diamond in the sky. \nTwinkle, twinkle, little star, \nHow I wonder what you are ")