# -*- coding: utf-8 -*-
"""Exercise 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yylEie0NcPYeaA48bd4lM9r_oiNXUe4Y
"""

print("Exercise 5\n")
radius=int(input("Enter radius: "))
total= 3.14*radius**2
print(total)