# -*- coding: utf-8 -*-
"""Exercise 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7fGL9kSIFDj38J6mI-axuxzS61rwnAc
"""

print("Exercise 3\n")
import datetime
now = datetime.datetime.now()
print ("Current date and time : ")
print (now.strftime("%Y-%m-%d %H:%M:%S"))