# -*- coding: utf-8 -*-
"""Exercise 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13CWnKhgPKFB47rBWzpd91wughUdqjmOT
"""

print("Exercise 4\n")
a="I "
b="am "
c="Raheem :)"
total= a+b+c
print(total)