# -*- coding: utf-8 -*-
"""Exercise 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wjln-jXGsQRddpx6_cVdwGOFuuQayX2C
"""

print("Exercise 2\n")
! python